"""initial schema

Revision ID: 4faaa84ceae0
Revises:
Create Date: 2022-10-09 21:22:25.109199

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4faaa84ceae0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("player_one", sa.Text(), nullable=False),
        sa.Column("player_two", sa.Text(), nullable=True),
        sa.Column("player_one_score", sa.Integer(), nullable=False),
        sa.Column("player_two_score", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "turn",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "player_one_move",
            sa.Enum(
                "ROCK", "PAPER", "SCISSORS", name="MOVE_ENUM", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column(
            "player_two_move",
            sa.Enum(
                "ROCK", "PAPER", "SCISSORS", name="MOVE_ENUM", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn")
    op.drop_table("game")
    # ### end Alembic commands ###
